'use client';

import React, { useState, useMemo } from 'react';
import { Terminal, Copy, Download, PlayCircle, Check } from 'lucide-react';
import { Button } from "@/components/ui/button";

export default function CodeTerminal({ nodes, edges }) {
  const [copied, setCopied] = useState(false);

  // Enhanced code generation logic
  const generateCode = useMemo(() => {
    let code = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title ChainChartContract
 * @dev Generated by ChainChart Builder
 */
contract ChainChartContract {
`;
    
    // State variables
    const stateNodes = nodes.filter(n => n.type === 'state');
    if (stateNodes.length > 0) {
      code += `    // State Variables\n`;
      stateNodes.forEach(n => {
        const type = n.metadata?.dataType || 'uint256';
        const visibility = n.metadata?.visibility || 'public';
        const name = (n.label || 'variable').replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '').toLowerCase() || 'variable';
        const value = n.value ? ` = ${n.value}` : '';
        code += `    ${type} ${visibility} ${name}${value};\n`;
      });
      code += `\n`;
    }

    // Events
    const eventNodes = nodes.filter(n => n.type === 'event');
    if (eventNodes.length > 0) {
      code += `    // Events\n`;
      eventNodes.forEach(n => {
        const name = (n.label || 'Event').replace(/\s+/g, '').replace(/[^a-zA-Z0-9_]/g, '') || 'Event';
        const params = n.metadata?.params || '';
        code += `    event ${name}(${params});\n`;
      });
      code += `\n`;
    } else {
      code += `    // Events\n    event Log(string message);\n\n`;
    }

    // Modifiers
    const modifierNodes = nodes.filter(n => n.type === 'modifier');
    if (modifierNodes.length > 0) {
      code += `    // Modifiers\n`;
      modifierNodes.forEach(n => {
        const name = (n.label || 'onlyOwner').replace(/\s+/g, '').replace(/[^a-zA-Z0-9_]/g, '') || 'onlyOwner';
        const expression = n.metadata?.expression || 'true';
        code += `    modifier ${name}() {\n        require(${expression}, "Access denied");\n        _;\n    }\n\n`;
      });
    }

    // Functions
    const functionNodes = nodes.filter(n => n.type === 'function');
    if (functionNodes.length > 0) {
      code += `    // Functions\n`;
      functionNodes.forEach((n, idx) => {
        const name = (n.label || 'myFunction').replace(/\s+/g, '').replace(/[^a-zA-Z0-9_]/g, '') || 'myFunction';
        const visibility = n.metadata?.visibility || 'public';
        const payable = n.metadata?.payable ? ' payable' : '';
        const params = n.metadata?.params || '';
        
        // Find connected modifiers (modifiers connected to this function)
        const connectedModifiers = edges
          .filter(e => {
            const [targetId] = e.to.split(':');
            return targetId === n.id;
          })
          .map(e => {
            const [sourceId] = e.from.split(':');
            const modifierNode = nodes.find(node => node.id === sourceId && node.type === 'modifier');
            return modifierNode;
          })
          .filter(Boolean)
          .map(m => (m.label || 'onlyOwner').replace(/\s+/g, '').replace(/[^a-zA-Z0-9_]/g, '') || 'onlyOwner');

        const modifierStr = connectedModifiers.length > 0 ? ` ${connectedModifiers.join(' ')}` : '';
        
        code += `    function ${name}(${params}) ${visibility}${payable}${modifierStr} {\n`;
        
        // Find connected operations and conditions
        const connectedOps = edges
          .filter(e => {
            const [sourceId] = e.from.split(':');
            return sourceId === n.id;
          })
          .map(e => {
            const [targetId] = e.to.split(':');
            return nodes.find(node => node.id === targetId);
          })
          .filter(Boolean);

        // Add logic based on connections
        if (connectedOps.length > 0) {
          connectedOps.forEach(op => {
            if (op.type === 'operation') {
              const opLabel = op.label || 'operation';
              code += `        // ${opLabel}\n`;
              if (op.value) {
                code += `        ${op.value};\n`;
              }
            } else if (op.type === 'condition') {
              const expression = op.metadata?.expression || 'true';
              const truePath = edges.find(e => {
                const [sourceId, sourcePos] = e.from.split(':');
                return sourceId === op.id && sourcePos === 'right';
              });
              const falsePath = edges.find(e => {
                const [sourceId, sourcePos] = e.from.split(':');
                return sourceId === op.id && sourcePos === 'bottom';
              });
              
              code += `        if (${expression}) {\n`;
              if (truePath) {
                code += `            // True path logic\n`;
              } else {
                code += `            // True path\n`;
              }
              code += `        }`;
              if (falsePath) {
                code += ` else {\n            // False path logic\n        }`;
              }
              code += `\n`;
            }
          });
        } else {
          code += `        // Add your logic here\n`;
        }

        // Find connected events
        const connectedEvents = edges
          .filter(e => {
            const [sourceId] = e.from.split(':');
            return sourceId === n.id;
          })
          .map(e => {
            const [targetId] = e.to.split(':');
            return nodes.find(node => node.id === targetId && node.type === 'event');
          })
          .filter(Boolean);

        connectedEvents.forEach(evt => {
          const eventName = (evt.label || 'Event').replace(/\s+/g, '').replace(/[^a-zA-Z0-9_]/g, '') || 'Event';
          code += `        emit ${eventName}();\n`;
        });

        if (connectedEvents.length === 0 && connectedOps.length === 0) {
          code += `        emit Log("${name} executed");\n`;
        }

        code += `    }\n`;
        if (idx < functionNodes.length - 1) code += `\n`;
      });
    } else {
      code += `    // Functions\n    function initialize() public {\n        // Initialize contract\n    }\n`;
    }

    code += `}`;
    return code;
  }, [nodes, edges]);

  const handleCopy = () => {
    navigator.clipboard.writeText(generateCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExport = () => {
    const blob = new Blob([generateCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ChainChartContract_${Date.now()}.sol`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="h-64 bg-black border-t border-white/10 flex flex-col font-mono text-sm z-20">
      <div className="flex items-center justify-between px-4 py-2 bg-white/5 border-b border-white/10">
        <div className="flex items-center gap-2">
          <Terminal className="w-4 h-4 text-emerald-green" />
          <span className="text-emerald-green font-bold text-xs tracking-widest uppercase">Live Preview</span>
        </div>
        <div className="flex items-center gap-2">
          <Button 
            size="sm" 
            variant="ghost" 
            className="h-7 text-xs text-gray-400 hover:text-white"
            onClick={handleCopy}
          >
            {copied ? (
              <>
                <Check className="w-3 h-3 mr-1" /> Copied!
              </>
            ) : (
              <>
                <Copy className="w-3 h-3 mr-1" /> Copy
              </>
            )}
          </Button>
          <Button 
            size="sm" 
            variant="ghost" 
            className="h-7 text-xs text-gray-400 hover:text-white"
            onClick={handleExport}
          >
            <Download className="w-3 h-3 mr-1" /> Export
          </Button>
        </div>
      </div>
      <div className="flex-1 p-4 overflow-auto relative custom-scrollbar">
        <pre className="text-gray-300 leading-relaxed font-mono text-xs">
          <code className="language-solidity whitespace-pre">
            {generateCode}
          </code>
        </pre>
      </div>
      <div className="px-4 py-3 border-t border-white/10 bg-white/5 flex justify-between items-center">
        <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-emerald-green rounded-full animate-pulse" />
            <span className="text-xs text-gray-400">Compiler Ready v0.8.19</span>
        </div>
        <Button className="bg-neon-yellow text-black hover:bg-[#DCD008] font-bold text-xs px-6">
            <PlayCircle className="w-4 h-4 mr-2" />
            DEPLOY TO TESTNET
        </Button>
      </div>
    </div>
  );
}